import {
  blackImg,
  blueImg,
  highlightFirstVideo,
  highlightFourthVideo,
  highlightSecondVideo,
  highlightThirdVideo,
  whiteImg,
  yellowImg,
} from "../utils";
import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  iPhoneX,
  iPhoneXs,
  iPhoneXsMax,
  iPhone11,
  iPhone11Pro,
  iPhone11ProMax,
  iPhone12,
  iPhone12Pro,
  iPhone12ProMax,
  iPhone13,
  iPhone13Pro,
  iPhone13ProMax,
  iPhone14,
  iPhone14Pro,
  iPhone14ProMax,
  iPhone16,
  iPhone16Pro,
  iPhone16ProMax,
  iPhone15,
  iPhone15Pro,
  iPhone15ProMax,
  MacBookAir13,
  MacBookAir15,
  MacBookPro14,
} from "../assets";
export const benefits = [
  {
    id: "0",
    title: "iPhone 16",
    text: "Enjoy the next generation of mobile technology with the iPhone 16. With a larger display and improved performance, this phone is perfect for daily use and entertainment.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone16,
  },
  {
    id: "1",
    title: " iPhone 16 Pro",
    text: "Discover powerful features and a sleek design with the iPhone 16 Pro. Its enhanced camera, advanced performance, and premium build make it the choice for tech enthusiasts.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: iPhone16Pro,
    light: true,
  },

  {
    id: "2",
    title: "iPhone 16 Pro Max",
    text: "Experience the ultimate in mobile technology with the iPhone 16 Pro Max. With its superior display, professional camera system, and exceptional performance, it’s ideal for creative professionals and photography lovers.",
    backgroundUrl: "./src/assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: iPhone16ProMax,
  },
  {
    id: "3",
    title: " iPhone 15 ",
    text: "The iPhone 15 combines cutting-edge technology with everyday functionality. Its advanced features and sleek design offer a balanced experience for all users.",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: iPhone15,
    light: true,
  },
  {
    id: "4",
    title: "iPhone 15 Pro",
    text: "The iPhone 15 Pro is designed for those who demand more. With an upgraded processor, improved camera, and premium build, it’s perfect for professional and personal use.",
    backgroundUrl: "./src/assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone15Pro,
  },
  {
    id: "5",
    title: "iPhone 15 Pro Max",
    text: "Get the best mobile experience with the iPhone 15 Pro Max. With its large display, powerful performance, and top-tier camera system, this phone is designed for professionals and those who want the very best.",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: iPhone15ProMax,
  },
];
export const benefits1 = [
  {
    id: "0",
    title: "iPhone 16",
    text: "Enjoy the next generation of mobile technology with the iPhone 16. With a larger display and improved performance, this phone is perfect for daily use and entertainment",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone16,
    price: "€949.00",
  },
  {
    id: "1",
    title: " iPhone 16 Pro",
    text: "Discover powerful features and a sleek design with the iPhone 16 Pro. Its enhanced camera, advanced performance, and premium build make it the choice for tech enthusiasts.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: iPhone16Pro,
    light: true,
    price: "€1100.00",
  },

  {
    id: "2",
    title: "iPhone 16 Pro Max",
    text: "Experience the ultimate in mobile technology with the iPhone 16 Pro Max. With its superior display, professional camera system, and exceptional performance, it’s ideal for creative professionals and photography lovers.",
    backgroundUrl: "./src/assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: iPhone16ProMax,
    price: "€1600.00",
  },
  {
    id: "3",
    title: " iPhone 15 ",
    text: "The iPhone 15 combines cutting-edge technology with everyday functionality. Its advanced features and sleek design offer a balanced experience for all users.",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: iPhone15,
    light: true,
    price: "€706.00",
  },
  {
    id: "4",
    title: "iPhone 15 Pro",
    text: "The iPhone 15 Pro is designed for those who demand more. With an upgraded processor, improved camera, and premium build, it’s perfect for professional and personal use.",
    backgroundUrl: "./src/assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone15Pro,
  },
  {
    id: "5",
    title: "iPhone 15 Pro Max",
    text: "Get the best mobile experience with the iPhone 15 Pro Max. With its large display, powerful performance, and top-tier camera system, this phone is designed for professionals and those who want the very best.",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: iPhone15ProMax,
  },
  {
    id: "6",
    title: "iPhone 14",
    text: "A classic choice for everyday use, the iPhone 14 provides a solid balance of performance and affordability with a dual-camera system.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone14,
  },
  {
    id: "7",
    title: "iPhone 14 Pro",
    text: "The iPhone 14 Pro features a sleek design, triple-camera system, and top-notch performance for all your needs.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone14Pro,
  },
  {
    id: "8",
    title: " iPhone 14 Pro Max",
    text: "With its expansive display and Pro camera system, the iPhone 14 Pro Max offers an unmatched smartphone experience for professionals and power users.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone14ProMax,
  },
  {
    id: "9",
    title: "iPhone 13",
    text: "A reliable smartphone with great battery life and a dual-camera system, offering a well-rounded experience for daily use.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone13,
  },
  {
    id: "10",
    title: " iPhone 13 Pro",
    text: "The iPhone 13 Pro features a high-resolution display and a Pro camera system that makes photography effortless and stunning.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone13Pro,
  },
  {
    id: "11",
    title: "iPhone 13 Pro Max ",
    text: "With its large display, triple-camera system, and advanced performance, the iPhone 13 Pro Max is a perfect device for professionals and tech enthusiasts.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone13ProMax,
  },
  {
    id: "12",
    title: "iPhone 12 ",
    text: "With a beautiful design and great performance, the iPhone 12 offers excellent value and solid features for everyday use.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone12,
  },
  {
    id: "13",
    title: "iPhone 12 Pro",
    text: "A stylish and powerful iPhone with a triple-camera system and Super Retina XDR display, great for multitasking and media.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone12Pro,
  },
  {
    id: "14",
    title: "iPhone 12 Pro Max",
    text: "With a massive display and advanced photography capabilities, the iPhone 12 Pro Max is perfect for those who need the best of the best.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone12ProMax,
  },
  {
    id: "15",
    title: "iPhone 11",
    text: "A durable and powerful phone with a dual-camera system and long battery life, the iPhone 11 is ideal for everyday tasks.",
    iconUrl: benefitIcon1,
    imageUrl: iPhone11,
  },
  {
    id: "16",
    title: "iPhone 11 Pro",
    text: "With a triple-camera system and Super Retina XDR display, the iPhone 11 Pro delivers professional-grade photography and performance.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone11Pro,
  },
  {
    id: "17",
    title: "iPhone 11 Pro Max",
    text: "Featuring a large display and the A13 Bionic chip, the iPhone 11 Pro Max offers a seamless user experience for all your needs.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhone11ProMax,
  },
  {
    id: "18",
    title: "iPhone X ",
    text: "A revolutionary design with Face ID and a stunning OLED display, the iPhone X set the standard for modern smartphones.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhoneX,
  },
  {
    id: "19",
    title: "iPhone XS",
    text: "Featuring a sleek design and impressive processing power, the iPhone XS is ideal for multitasking and media consumption.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhoneXs,
  },
  {
    id: "20",
    title: " iPhone XS",
    text: "The iPhone XS Max boasts a large display and an advanced dual-camera system for capturing high-quality images and videos.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: iPhoneXsMax,
  },
  {
    id: "21",
    title: "MacBook Pro 16-inch",
    text: "The ultimate powerhouse for professionals, featuring the M2 Max chip, a stunning Liquid Retina XDR display, and incredible battery life for demanding tasks like video editing and 3D rendering.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookPro14,
  },
  {
    id: "22",
    title: "MacBook Pro 14-inch",
    text: "A perfect balance of power and portability, the MacBook Pro 14-inch offers impressive performance with the M2 Pro chip and a stunning high-resolution display for all your professional needs.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookPro14,
  },
  {
    id: "23",
    title: "MacBook Air 15-inch (M2)",
    text: "The 15-inch MacBook Air with M2 is the ultimate lightweight laptop with a large display, perfect for everyday tasks, video streaming, and light creative work, all while maintaining impressive battery life.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookAir15,
  },
  {
    id: "24",
    title: "MacBook Air 13-inch",
    text: "A super-slim and powerful laptop, the 13-inch MacBook Air with M2 offers all-day battery life, a vibrant Retina display, and exceptional portability for users who need both power and mobility.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookAir13,
  },
  {
    id: "25",
    title: "MacBook Pro 16-inch (M2 Max)",
    text: "The most powerful MacBook, featuring the M2 Max chip, a stunning 16-inch Liquid Retina XDR display, and exceptional battery life for intensive tasks like video editing and 3D graphics.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookPro14,
  },
  {
    id: "26",
    title: "MacBook Pro 14-inch (M2 Max)",
    text: "This 14-inch MacBook Pro offers professional-grade performance in a compact form, powered by the M2 Pro chip, ideal for software development, design, and multitasking.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: MacBookPro14,
  },
];
export const navLists = ["Home", "Shop", "Cart", "Dashboard"];

export const navList = ["Sign up", "Sign in"];

export const hightlightsSlides = [
  {
    id: 1,
    textLists: [
      "Enter A17 Pro.",
      "Game‑changing chip.",
      "Groundbreaking performance.",
    ],
    video: highlightFirstVideo,
    videoDuration: 4,
  },
  {
    id: 2,
    textLists: ["Titanium.", "So strong. So light. So Pro."],
    video: highlightSecondVideo,
    videoDuration: 5,
  },
  {
    id: 3,
    textLists: [
      "iPhone 15 Pro Max has the",
      "longest optical zoom in",
      "iPhone ever. Far out.",
    ],
    video: highlightThirdVideo,
    videoDuration: 2,
  },
  {
    id: 4,
    textLists: ["All-new Action button.", "What will yours do?."],
    video: highlightFourthVideo,
    videoDuration: 3.63,
  },
];

export const models = [
  {
    id: 1,
    title: "iPhone 15 Pro in Natural Titanium",
    color: ["#8F8A81", "#ffe7b9", "#6f6c64"],
    img: yellowImg,
  },
  {
    id: 2,
    title: "iPhone 15 Pro in Blue Titanium",
    color: ["#53596E", "#6395ff", "#21242e"],
    img: blueImg,
  },
  {
    id: 3,
    title: "iPhone 15 Pro in White Titanium",
    color: ["#C9C8C2", "#ffffff", "#C9C8C2"],
    img: whiteImg,
  },
  {
    id: 4,
    title: "iPhone 15 Pro in Black Titanium",
    color: ["#454749", "#3b3b3b", "#181819"],
    img: blackImg,
  },
];

export const sizes = [
  { label: '6.1"', value: "small" },
  { label: '6.7"', value: "large" },
];

export const footerLinks = [
  "Privacy Policy",
  "Terms of Use",
  "Sales Policy",
  "Legal",
  "Site Map",
];
